#cloud-config
repo_update: true
repo_upgrade: all

runcmd:

  # update
  - echo "Starting CloudInit userdata"
  - yum update -y

  # install tools
  - amazon-linux-extras install -y epel
  - dnf groupinstall -y "Development Tools"
#  - dnf install -y parallel ioping tree nload git libaio-devel openmpi openmpi-devel
